language: python
python:
  - 3.8
  - 3.7
  - 3.6
  - 3.5
sudo: false
dist: xenial
services:
  - xvfb
addons:
  chrome: stable
  apt_packages:
    - pandoc
env:
  matrix:
    - GROUP=python
matrix:
  include:
    - python: 3.5
      env: GROUP=js
cache:
  pip: true
  directories:
    - ipydatawidgets/jlextension/node_modules # NPM packages
    - node_modules # NPM packages
    - $HOME/.npm
before_install:
  - pip install -U pip setuptools
  - nvm install 8
  - |
    if [[ $GROUP == python ]]; then
      pip install codecov
    elif [[ $GROUP == js ]]; then
      npm install -g codecov
    fi
install:
  - |
    if [[ $GROUP == python ]]; then
      pip install --upgrade ".[test]" -v
    elif [[ $GROUP == js ]]; then
      pip install --upgrade -e ".[test]" -v
    fi
before_script:
  # Set up a virtual screen for Firefox browser testing:
  - |
    if [[ $GROUP == js ]]; then
      export CHROME_BIN=google-chrome-stable
    fi
    git config --global user.email travis@fake.com
    git config --global user.name "Travis CI"
script:
  - |
    EXIT_STATUS=0
    if [[ $GROUP == python ]]; then
      pushd $(mktemp -d)
      py.test -l --cov-report xml:$TRAVIS_BUILD_DIR/coverage.xml --cov=ipydatawidgets --pyargs ipydatawidgets || EXIT_STATUS=$?
      py.test -l --cov-report xml:$TRAVIS_BUILD_DIR/coverage.xml --cov=ipydatawidgets $TRAVIS_BUILD_DIR/examples || EXIT_STATUS=$?
      popd
    elif [[ $GROUP == js ]]; then
      npm run test:ci || EXIT_STATUS=$?
    fi
    (exit $EXIT_STATUS)
before_cache:
  # Do not cache our own package
  - |
    rm -rf packages/jupyterlab-datawidgets/node_modules/jupyter-datawidgets
after_success:
  - codecov
